### ISSUE TITLE
steppers pause when send gcode via websocket

### ISSUE THREAD

**Issue by MillerRen** [gcobos/grblesp#7]
hi @gcobos thank you  create this great object. It works fine by usb serial but websocket. Steppers always paused and run agin later. I gess maybe the timer0 issue. Timer0 used by wifi feature,but steppers pluse used timer0 too. Have you faced this problem?

**Comment by gcobos** [comment]
Hi! Thanks for trying this out. The support for websockets is not fully tested. What are you using as the client for websocket?

**Comment by MillerRen** [comment]
lasergrbl

**Comment by gcobos** [comment]
Thanks, I'll check it out on the weekend

**Comment by gcobos** [comment]
I would recommend to not to use this project with lasergrbl. Many of the fuctionalities of GRBL are not enabled, and only the motor control is ensured to work. I would choose something like https://github.com/bdring/Grbl_Esp32 which has much more support, but you will then need an ESP32, instead of a ESP8266

**Comment by MillerRen** [comment]
Thank you for your advice. I am porting this to a pen plotter or laser engraver. Esp8266 has enough pins. It's a nice things that a 2 axis cnc powered by esp8266 without external ic. Because esp8266 is cheap and simple :-)
